In [1]:
import random
import numpy as np

In [103]:
population = 4
mutations = 0.25

In [14]:

colors = [0,1,2,3,4,5]

board = random.choices(colors,k=4)
print(board)

[0, 5, 4, 3]


In [86]:
choice = random.choices(colors,k=4)
print(choice)

def score(board, choice):

    tmp_board = board.copy()

    in_place = 0
    in_place_list = []
    same_color = 0

    for i,c in enumerate(choice):
        if choice[i] == board[i]:
            in_place += 1
            in_place_list.append(i)
            tmp_board[i] = -1

    for i,c in enumerate(choice):
        if i not in in_place_list:
            if c in tmp_board:
                same_color += 1

    return (2 * in_place) + same_color
    #return (2 * in_place)


[0, 0, 3, 1]


In [104]:
def ga(board):

    mem = np.random.randint(6, size=(2 * population, 4))

    scores = np.zeros((2 * population))

    for i in range(100000000):

        for k, matrix in enumerate(mem):
            scores[k] = score(board, matrix)

        max_score = np.argmax(scores)

        if scores[max_score] == 8:
            print(i)
            print(mem[max_score])  # use appropriate colormap here
            break

        top_n_scores = np.argpartition(scores, -population)

        top = top_n_scores[-population:]
        bottom = top_n_scores[:-population]

        mid = 4//2

        for j in range(population):
            
            r = random.randrange(len(top))  
            idx = [r, (r+1)%len(top)]
            parents = [top[idx[0]],top[idx[1]]]
            
            mem[bottom[j]][0:mid] = mem[parents[0]][0:mid]
            mem[bottom[j]][-(mid):] = mem[parents[1]][-(mid):]

            idx = np.random.choice([0,1,2,3,4,5,6], p=[(1-mutations), mutations/6,mutations/6,mutations/6,mutations/6,mutations/6,mutations/6],size=(4))

            for k in range(len(idx)):
                mem[bottom[j]][k] = (mem[bottom[j]][k] + idx[k])%6


In [105]:
ga(board)

37
[0 5 4 3]


In [61]:
board

[0, 0, 1, 5]

In [44]:
import numpy as np

mutations = 0.2

idx = np.random.choice([0,1,2,3,4,5,6], p=[(1-mutations), mutations/6,mutations/6,mutations/6,mutations/6,mutations/6,mutations/6],size=(10))

idx

array([0, 0, 6, 0, 0, 0, 0, 0, 0, 0])

In [29]:
idx

array([2, 5, 4, 5, 0, 1, 6, 0, 2, 3])

In [3]:
4//2
l = [0,1,2,3]

In [6]:
l[-(2):]

[2, 3]

In [53]:
ga(board)

148
[0 0 1 5]


In [51]:
np.random.choice([0,1], p=[(1-mutations), mutations],size=(4))

array([1, 1, 1, 0])