In [2]:
import random
import numpy as np

In [25]:
population = 2
mutations = 0.25

In [4]:

colors = [0,1,2,3,4,5]

board = random.choices(colors,k=4)
print(board)

[3, 2, 3, 5]


In [312]:
def score(board, choice):

    tmp_board = board.copy()

    in_place = 0
    in_place_list = []
    same_color = 0

    for i,c in enumerate(choice):
        if choice[i] == board[i]:
            in_place += 1
            in_place_list.append(i)
            tmp_board[i] = -1

    for i,c in enumerate(choice):
        if i not in in_place_list:
            if c in tmp_board:
                same_color += 1

    #return (2 * in_place) + same_color
    return (2 * in_place)


In [137]:
def ga2(array, population, mutations):

    score_memoization = {}

    def score(board, choice):
        
        key = tuple(choice)
        
        # if key in score_memoization:
        #     return score_memoization[key]

        tmp_board = board.copy()

        in_place = 0
        in_place_list = set()
        same_color = 0

        for i in range(len(choice)):
            if choice[i] == board[i]:
                in_place += 1
                in_place_list.add(i)
                tmp_board[i] = -1

        for i,c in enumerate(choice):
            if i not in in_place_list and c in tmp_board:
                same_color += 1

        score = (3 * in_place) + same_color
        #score = in_place
        score_memoization[key] = score

        return score

    mid = 4//2

    mem = np.random.randint(6, size=(2 * population, 4))
    scores = np.zeros((2 * population))
    bottom = list(range(len(mem)))

    for i in range(1000000):
        
        # Bottom will contain all the random individuals generated when starting the execution
        # and the new individuals after the first iteration. Bottom means the bottom of the list
        # sorted by score
        for k in bottom:
            scores[k] = score(array, mem[k])

        # Check if the solution has been found
        max_score = np.argmax(scores)
        if scores[max_score] == 12:
            return i, len(score_memoization)

        # Select the population of individuals according to the score function
        top_n_scores = np.argpartition(scores, population)
        top = top_n_scores[population:]
        bottom = top_n_scores[:population]

        # Create #population new elements from the crossover and mutation
        for j in range(population):

            # Crossover -> Select parents from the top individuals
            #
            # I tried this with random choice and just picking a random position
            # from the top and the next one and the result is the same but way faster
            # It might be because of either the randomization of the initial population or maybe
            # the implementation of argpartition? or both?
            
            r = random.randrange(len(top))  
            idx = [r, (r+1)%len(top)]
            parents = [top[idx[0]],top[idx[1]]]
            
            mem[bottom[j]][0:mid] = mem[parents[0]][0:mid]
            mem[bottom[j]][-(mid):] = mem[parents[1]][-(mid):]

            # Mutation -> Mutate the bits
            #
            # The random choice of the bits to mutate is the most costly of the implementation
            # It seems there has to be some way to speed up this 
            idx = np.random.choice([0,1,2,3,4,5,6], p=[(1-mutations), mutations/6,mutations/6,mutations/6,mutations/6,mutations/6,mutations/6],size=(4))

            for k in range(len(idx)):
                mem[bottom[j]][k] = (mem[bottom[j]][k] + idx[k])%6

In [134]:
ga2(board, population, mutations)

(11, 22)

In [316]:
def ga(board):

    mem = np.random.randint(6, size=(2 * population, 4))

    scores = np.zeros((2 * population))

    for i in range(100000000):

        for k, matrix in enumerate(mem):
            scores[k] = score(board, matrix)

        max_score = np.argmax(scores)

        if scores[max_score] == 8:
            return i

        top_n_scores = np.argpartition(scores, -population)

        top = top_n_scores[-population:]
        bottom = top_n_scores[:-population]

        mid = 4//2

        for j in range(population):
            
            r = random.randrange(len(top))  
            idx = [r, (r+1)%len(top)]
            parents = [top[idx[0]],top[idx[1]]]
            
            mem[bottom[j]][0:mid] = mem[parents[0]][0:mid]
            mem[bottom[j]][-(mid):] = mem[parents[1]][-(mid):]

            idx = np.random.choice([0,1,2,3,4,5,6], p=[(1-mutations), mutations/6,mutations/6,mutations/6,mutations/6,mutations/6,mutations/6],size=(4))

            for k in range(len(idx)):
                mem[bottom[j]][k] = (mem[bottom[j]][k] + idx[k])%6


In [142]:
trials = 1000

population = 4
mutations = 0.25

accum1 = 0
accum2 = 0

for i in range(trials):
    iters, mem = ga2(board, population, mutations)
    accum1 += iters
    accum2 += mem

print (accum1/trials)
print (accum2/trials)

16.653
42.922


In [339]:
trials = 10000

accum = 0

for i in range(trials):
 #accum += ga(board, population, mutations)
 accum += ga(board)

print (accum/trials)

16.0621


In [61]:
board

[0, 0, 1, 5]

In [44]:
import numpy as np

mutations = 0.2

idx = np.random.choice([0,1,2,3,4,5,6], p=[(1-mutations), mutations/6,mutations/6,mutations/6,mutations/6,mutations/6,mutations/6],size=(10))

idx

array([0, 0, 6, 0, 0, 0, 0, 0, 0, 0])

In [29]:
idx

array([2, 5, 4, 5, 0, 1, 6, 0, 2, 3])

In [3]:
4//2
l = [0,1,2,3]

In [6]:
l[-(2):]

[2, 3]

In [53]:
ga(board)

148
[0 0 1 5]


In [51]:
np.random.choice([0,1], p=[(1-mutations), mutations],size=(4))

array([1, 1, 1, 0])